#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
		
	public partial class adbdDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblFile(tblFile instance);
    partial void UpdatetblFile(tblFile instance);
    partial void DeletetblFile(tblFile instance);
    partial void InserttblFolder(tblFolder instance);
    partial void UpdatetblFolder(tblFolder instance);
    partial void DeletetblFolder(tblFolder instance);
    partial void InserttblFolderFile(tblFolderFile instance);
    partial void UpdatetblFolderFile(tblFolderFile instance);
    partial void DeletetblFolderFile(tblFolderFile instance);
    partial void InserttblLanguage(tblLanguage instance);
    partial void UpdatetblLanguage(tblLanguage instance);
    partial void DeletetblLanguage(tblLanguage instance);
    partial void InserttblProdctFile(tblProdctFile instance);
    partial void UpdatetblProdctFile(tblProdctFile instance);
    partial void DeletetblProdctFile(tblProdctFile instance);
    partial void InserttblProduct(tblProduct instance);
    partial void UpdatetblProduct(tblProduct instance);
    partial void DeletetblProduct(tblProduct instance);
    partial void InserttblProductAddOn(tblProductAddOn instance);
    partial void UpdatetblProductAddOn(tblProductAddOn instance);
    partial void DeletetblProductAddOn(tblProductAddOn instance);
    partial void InserttblUser(tblUser instance);
    partial void UpdatetblUser(tblUser instance);
    partial void DeletetblUser(tblUser instance);
    partial void InserttblUserType(tblUserType instance);
    partial void UpdatetblUserType(tblUserType instance);
    partial void DeletetblUserType(tblUserType instance);
    partial void InserttblProductCategory(tblProductCategory instance);
    partial void UpdatetblProductCategory(tblProductCategory instance);
    partial void DeletetblProductCategory(tblProductCategory instance);
    partial void InserttblProductGroup(tblProductGroup instance);
    partial void UpdatetblProductGroup(tblProductGroup instance);
    partial void DeletetblProductGroup(tblProductGroup instance);
    #endregion
		
				
		public adbdDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}		
		
		public System.Data.Linq.Table<tblFile> tblFiles
		{
			get
			{
				return this.GetTable<tblFile>();
			}
		}
		
		public System.Data.Linq.Table<tblFolder> tblFolders
		{
			get
			{
				return this.GetTable<tblFolder>();
			}
		}
		
		public System.Data.Linq.Table<tblFolderFile> tblFolderFiles
		{
			get
			{
				return this.GetTable<tblFolderFile>();
			}
		}
		
		public System.Data.Linq.Table<tblLanguage> tblLanguages
		{
			get
			{
				return this.GetTable<tblLanguage>();
			}
		}
		
		public System.Data.Linq.Table<tblProdctFile> tblProdctFiles
		{
			get
			{
				return this.GetTable<tblProdctFile>();
			}
		}
		
		public System.Data.Linq.Table<tblProduct> tblProducts
		{
			get
			{
				return this.GetTable<tblProduct>();
			}
		}
		
		public System.Data.Linq.Table<tblProductAddOn> tblProductAddOns
		{
			get
			{
				return this.GetTable<tblProductAddOn>();
			}
		}
		
		public System.Data.Linq.Table<tblUser> tblUsers
		{
			get
			{
				return this.GetTable<tblUser>();
			}
		}
		
		public System.Data.Linq.Table<tblUserType> tblUserTypes
		{
			get
			{
				return this.GetTable<tblUserType>();
			}
		}
		
		public System.Data.Linq.Table<tblProductCategory> tblProductCategories
		{
			get
			{
				return this.GetTable<tblProductCategory>();
			}
		}
		
		public System.Data.Linq.Table<tblProductGroup> tblProductGroups
		{
			get
			{
				return this.GetTable<tblProductGroup>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblFile")]
	public partial class tblFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FilId;
		
		private System.DateTime _RegDato;
		
		private string _Filnavn;
		
		private string _Etternavn;
		
		private string _Filtype;
		
		private string _Bredde;
		
		private string _Hoyde;
		
		private string _Storrelse;
		
		private string _Beskrivelse;
		
		private EntitySet<tblFolderFile> _tblFolderFiles;
		
		private EntitySet<tblProdctFile> _tblProdctFiles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFilIdChanging(int value);
    partial void OnFilIdChanged();
    partial void OnRegDatoChanging(System.DateTime value);
    partial void OnRegDatoChanged();
    partial void OnFilnavnChanging(string value);
    partial void OnFilnavnChanged();
    partial void OnEtternavnChanging(string value);
    partial void OnEtternavnChanged();
    partial void OnFiltypeChanging(string value);
    partial void OnFiltypeChanged();
    partial void OnBreddeChanging(string value);
    partial void OnBreddeChanged();
    partial void OnHoydeChanging(string value);
    partial void OnHoydeChanged();
    partial void OnStorrelseChanging(string value);
    partial void OnStorrelseChanged();
    partial void OnBeskrivelseChanging(string value);
    partial void OnBeskrivelseChanged();
    #endregion
		
		public tblFile()
		{
			this._tblFolderFiles = new EntitySet<tblFolderFile>(new Action<tblFolderFile>(this.attach_tblFolderFiles), new Action<tblFolderFile>(this.detach_tblFolderFiles));
			this._tblProdctFiles = new EntitySet<tblProdctFile>(new Action<tblProdctFile>(this.attach_tblProdctFiles), new Action<tblProdctFile>(this.detach_tblProdctFiles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FilId
		{
			get
			{
				return this._FilId;
			}
			set
			{
				if ((this._FilId != value))
				{
					this.OnFilIdChanging(value);
					this.SendPropertyChanging();
					this._FilId = value;
					this.SendPropertyChanged("FilId");
					this.OnFilIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegDato", DbType="Date NOT NULL")]
		public System.DateTime RegDato
		{
			get
			{
				return this._RegDato;
			}
			set
			{
				if ((this._RegDato != value))
				{
					this.OnRegDatoChanging(value);
					this.SendPropertyChanging();
					this._RegDato = value;
					this.SendPropertyChanged("RegDato");
					this.OnRegDatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filnavn", DbType="NVarChar(255)")]
		public string Filnavn
		{
			get
			{
				return this._Filnavn;
			}
			set
			{
				if ((this._Filnavn != value))
				{
					this.OnFilnavnChanging(value);
					this.SendPropertyChanging();
					this._Filnavn = value;
					this.SendPropertyChanged("Filnavn");
					this.OnFilnavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etternavn", DbType="NVarChar(255)")]
		public string Etternavn
		{
			get
			{
				return this._Etternavn;
			}
			set
			{
				if ((this._Etternavn != value))
				{
					this.OnEtternavnChanging(value);
					this.SendPropertyChanging();
					this._Etternavn = value;
					this.SendPropertyChanged("Etternavn");
					this.OnEtternavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filtype", DbType="NVarChar(255)")]
		public string Filtype
		{
			get
			{
				return this._Filtype;
			}
			set
			{
				if ((this._Filtype != value))
				{
					this.OnFiltypeChanging(value);
					this.SendPropertyChanging();
					this._Filtype = value;
					this.SendPropertyChanged("Filtype");
					this.OnFiltypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bredde", DbType="NVarChar(255)")]
		public string Bredde
		{
			get
			{
				return this._Bredde;
			}
			set
			{
				if ((this._Bredde != value))
				{
					this.OnBreddeChanging(value);
					this.SendPropertyChanging();
					this._Bredde = value;
					this.SendPropertyChanged("Bredde");
					this.OnBreddeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoyde", DbType="NVarChar(255)")]
		public string Hoyde
		{
			get
			{
				return this._Hoyde;
			}
			set
			{
				if ((this._Hoyde != value))
				{
					this.OnHoydeChanging(value);
					this.SendPropertyChanging();
					this._Hoyde = value;
					this.SendPropertyChanged("Hoyde");
					this.OnHoydeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Storrelse", DbType="NVarChar(255)")]
		public string Storrelse
		{
			get
			{
				return this._Storrelse;
			}
			set
			{
				if ((this._Storrelse != value))
				{
					this.OnStorrelseChanging(value);
					this.SendPropertyChanging();
					this._Storrelse = value;
					this.SendPropertyChanged("Storrelse");
					this.OnStorrelseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beskrivelse", DbType="NVarChar(MAX)")]
		public string Beskrivelse
		{
			get
			{
				return this._Beskrivelse;
			}
			set
			{
				if ((this._Beskrivelse != value))
				{
					this.OnBeskrivelseChanging(value);
					this.SendPropertyChanging();
					this._Beskrivelse = value;
					this.SendPropertyChanged("Beskrivelse");
					this.OnBeskrivelseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFile_tblFolderFile", Storage="_tblFolderFiles", ThisKey="FilId", OtherKey="FilId")]
		public EntitySet<tblFolderFile> tblFolderFiles
		{
			get
			{
				return this._tblFolderFiles;
			}
			set
			{
				this._tblFolderFiles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFile_tblProdctFile", Storage="_tblProdctFiles", ThisKey="FilId", OtherKey="FilId")]
		public EntitySet<tblProdctFile> tblProdctFiles
		{
			get
			{
				return this._tblProdctFiles;
			}
			set
			{
				this._tblProdctFiles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblFolderFiles(tblFolderFile entity)
		{
			this.SendPropertyChanging();
			entity.tblFile = this;
		}
		
		private void detach_tblFolderFiles(tblFolderFile entity)
		{
			this.SendPropertyChanging();
			entity.tblFile = null;
		}
		
		private void attach_tblProdctFiles(tblProdctFile entity)
		{
			this.SendPropertyChanging();
			entity.tblFile = this;
		}
		
		private void detach_tblProdctFiles(tblProdctFile entity)
		{
			this.SendPropertyChanging();
			entity.tblFile = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblFolder")]
	public partial class tblFolder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MappeId;
		
		private System.Nullable<int> _BrukerId;
		
		private System.Nullable<int> _KnyttetId;
		
		private System.Nullable<int> _Nivaa;
		
		private string _Mappenavn;
		
		private string _Mappetype;
		
		private System.Nullable<int> _MappeStrukturId;
		
		private EntitySet<tblFolderFile> _tblFolderFiles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMappeIdChanging(int value);
    partial void OnMappeIdChanged();
    partial void OnBrukerIdChanging(System.Nullable<int> value);
    partial void OnBrukerIdChanged();
    partial void OnKnyttetIdChanging(System.Nullable<int> value);
    partial void OnKnyttetIdChanged();
    partial void OnNivaaChanging(System.Nullable<int> value);
    partial void OnNivaaChanged();
    partial void OnMappenavnChanging(string value);
    partial void OnMappenavnChanged();
    partial void OnMappetypeChanging(string value);
    partial void OnMappetypeChanged();
    partial void OnMappeStrukturIdChanging(System.Nullable<int> value);
    partial void OnMappeStrukturIdChanged();
    #endregion
		
		public tblFolder()
		{
			this._tblFolderFiles = new EntitySet<tblFolderFile>(new Action<tblFolderFile>(this.attach_tblFolderFiles), new Action<tblFolderFile>(this.detach_tblFolderFiles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MappeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MappeId
		{
			get
			{
				return this._MappeId;
			}
			set
			{
				if ((this._MappeId != value))
				{
					this.OnMappeIdChanging(value);
					this.SendPropertyChanging();
					this._MappeId = value;
					this.SendPropertyChanged("MappeId");
					this.OnMappeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrukerId", DbType="Int")]
		public System.Nullable<int> BrukerId
		{
			get
			{
				return this._BrukerId;
			}
			set
			{
				if ((this._BrukerId != value))
				{
					this.OnBrukerIdChanging(value);
					this.SendPropertyChanging();
					this._BrukerId = value;
					this.SendPropertyChanged("BrukerId");
					this.OnBrukerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KnyttetId", DbType="Int")]
		public System.Nullable<int> KnyttetId
		{
			get
			{
				return this._KnyttetId;
			}
			set
			{
				if ((this._KnyttetId != value))
				{
					this.OnKnyttetIdChanging(value);
					this.SendPropertyChanging();
					this._KnyttetId = value;
					this.SendPropertyChanged("KnyttetId");
					this.OnKnyttetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivaa", DbType="Int")]
		public System.Nullable<int> Nivaa
		{
			get
			{
				return this._Nivaa;
			}
			set
			{
				if ((this._Nivaa != value))
				{
					this.OnNivaaChanging(value);
					this.SendPropertyChanging();
					this._Nivaa = value;
					this.SendPropertyChanged("Nivaa");
					this.OnNivaaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mappenavn", DbType="NVarChar(255)")]
		public string Mappenavn
		{
			get
			{
				return this._Mappenavn;
			}
			set
			{
				if ((this._Mappenavn != value))
				{
					this.OnMappenavnChanging(value);
					this.SendPropertyChanging();
					this._Mappenavn = value;
					this.SendPropertyChanged("Mappenavn");
					this.OnMappenavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mappetype", DbType="NVarChar(255)")]
		public string Mappetype
		{
			get
			{
				return this._Mappetype;
			}
			set
			{
				if ((this._Mappetype != value))
				{
					this.OnMappetypeChanging(value);
					this.SendPropertyChanging();
					this._Mappetype = value;
					this.SendPropertyChanged("Mappetype");
					this.OnMappetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MappeStrukturId", DbType="Int")]
		public System.Nullable<int> MappeStrukturId
		{
			get
			{
				return this._MappeStrukturId;
			}
			set
			{
				if ((this._MappeStrukturId != value))
				{
					this.OnMappeStrukturIdChanging(value);
					this.SendPropertyChanging();
					this._MappeStrukturId = value;
					this.SendPropertyChanged("MappeStrukturId");
					this.OnMappeStrukturIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFolder_tblFolderFile", Storage="_tblFolderFiles", ThisKey="MappeId", OtherKey="MappeId")]
		public EntitySet<tblFolderFile> tblFolderFiles
		{
			get
			{
				return this._tblFolderFiles;
			}
			set
			{
				this._tblFolderFiles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblFolderFiles(tblFolderFile entity)
		{
			this.SendPropertyChanging();
			entity.tblFolder = this;
		}
		
		private void detach_tblFolderFiles(tblFolderFile entity)
		{
			this.SendPropertyChanging();
			entity.tblFolder = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblFolderFile")]
	public partial class tblFolderFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MappeFilId;
		
		private System.Nullable<int> _MappeId;
		
		private System.Nullable<int> _FilId;
		
		private EntityRef<tblFile> _tblFile;
		
		private EntityRef<tblFolder> _tblFolder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMappeFilIdChanging(int value);
    partial void OnMappeFilIdChanged();
    partial void OnMappeIdChanging(System.Nullable<int> value);
    partial void OnMappeIdChanged();
    partial void OnFilIdChanging(System.Nullable<int> value);
    partial void OnFilIdChanged();
    #endregion
		
		public tblFolderFile()
		{
			this._tblFile = default(EntityRef<tblFile>);
			this._tblFolder = default(EntityRef<tblFolder>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MappeFilId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MappeFilId
		{
			get
			{
				return this._MappeFilId;
			}
			set
			{
				if ((this._MappeFilId != value))
				{
					this.OnMappeFilIdChanging(value);
					this.SendPropertyChanging();
					this._MappeFilId = value;
					this.SendPropertyChanged("MappeFilId");
					this.OnMappeFilIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MappeId", DbType="Int")]
		public System.Nullable<int> MappeId
		{
			get
			{
				return this._MappeId;
			}
			set
			{
				if ((this._MappeId != value))
				{
					if (this._tblFolder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMappeIdChanging(value);
					this.SendPropertyChanging();
					this._MappeId = value;
					this.SendPropertyChanged("MappeId");
					this.OnMappeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilId", DbType="Int")]
		public System.Nullable<int> FilId
		{
			get
			{
				return this._FilId;
			}
			set
			{
				if ((this._FilId != value))
				{
					if (this._tblFile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFilIdChanging(value);
					this.SendPropertyChanging();
					this._FilId = value;
					this.SendPropertyChanged("FilId");
					this.OnFilIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFile_tblFolderFile", Storage="_tblFile", ThisKey="FilId", OtherKey="FilId", IsForeignKey=true)]
		public tblFile tblFile
		{
			get
			{
				return this._tblFile.Entity;
			}
			set
			{
				tblFile previousValue = this._tblFile.Entity;
				if (((previousValue != value) 
							|| (this._tblFile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblFile.Entity = null;
						previousValue.tblFolderFiles.Remove(this);
					}
					this._tblFile.Entity = value;
					if ((value != null))
					{
						value.tblFolderFiles.Add(this);
						this._FilId = value.FilId;
					}
					else
					{
						this._FilId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblFile");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFolder_tblFolderFile", Storage="_tblFolder", ThisKey="MappeId", OtherKey="MappeId", IsForeignKey=true)]
		public tblFolder tblFolder
		{
			get
			{
				return this._tblFolder.Entity;
			}
			set
			{
				tblFolder previousValue = this._tblFolder.Entity;
				if (((previousValue != value) 
							|| (this._tblFolder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblFolder.Entity = null;
						previousValue.tblFolderFiles.Remove(this);
					}
					this._tblFolder.Entity = value;
					if ((value != null))
					{
						value.tblFolderFiles.Add(this);
						this._MappeId = value.MappeId;
					}
					else
					{
						this._MappeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblFolder");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLanguage")]
	public partial class tblLanguage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LanguageId;
		
		private string _Language;
		
		private string _LanguageCode;
		
		private EntitySet<tblUser> _tblUsers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLanguageIdChanging(int value);
    partial void OnLanguageIdChanged();
    partial void OnLanguageChanging(string value);
    partial void OnLanguageChanged();
    partial void OnLanguageCodeChanging(string value);
    partial void OnLanguageCodeChanged();
    #endregion
		
		public tblLanguage()
		{
			this._tblUsers = new EntitySet<tblUser>(new Action<tblUser>(this.attach_tblUsers), new Action<tblUser>(this.detach_tblUsers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LanguageId
		{
			get
			{
				return this._LanguageId;
			}
			set
			{
				if ((this._LanguageId != value))
				{
					this.OnLanguageIdChanging(value);
					this.SendPropertyChanging();
					this._LanguageId = value;
					this.SendPropertyChanged("LanguageId");
					this.OnLanguageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this.OnLanguageChanging(value);
					this.SendPropertyChanging();
					this._Language = value;
					this.SendPropertyChanged("Language");
					this.OnLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this.OnLanguageCodeChanging(value);
					this.SendPropertyChanging();
					this._LanguageCode = value;
					this.SendPropertyChanged("LanguageCode");
					this.OnLanguageCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLanguage_tblUser", Storage="_tblUsers", ThisKey="LanguageId", OtherKey="LanguageId")]
		public EntitySet<tblUser> tblUsers
		{
			get
			{
				return this._tblUsers;
			}
			set
			{
				this._tblUsers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblUsers(tblUser entity)
		{
			this.SendPropertyChanging();
			entity.tblLanguage = this;
		}
		
		private void detach_tblUsers(tblUser entity)
		{
			this.SendPropertyChanging();
			entity.tblLanguage = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProdctFile")]
	public partial class tblProdctFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProduktBildeId;
		
		private System.Nullable<int> _ProduktId;
		
		private System.Nullable<int> _FilId;
		
		private System.Nullable<int> _Sort;
		
		private string _TypeFil;
		
		private EntityRef<tblFile> _tblFile;
		
		private EntityRef<tblProduct> _tblProduct;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduktBildeIdChanging(int value);
    partial void OnProduktBildeIdChanged();
    partial void OnProduktIdChanging(System.Nullable<int> value);
    partial void OnProduktIdChanged();
    partial void OnFilIdChanging(System.Nullable<int> value);
    partial void OnFilIdChanged();
    partial void OnSortChanging(System.Nullable<int> value);
    partial void OnSortChanged();
    partial void OnTypeFilChanging(string value);
    partial void OnTypeFilChanged();
    #endregion
		
		public tblProdctFile()
		{
			this._tblFile = default(EntityRef<tblFile>);
			this._tblProduct = default(EntityRef<tblProduct>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktBildeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProduktBildeId
		{
			get
			{
				return this._ProduktBildeId;
			}
			set
			{
				if ((this._ProduktBildeId != value))
				{
					this.OnProduktBildeIdChanging(value);
					this.SendPropertyChanging();
					this._ProduktBildeId = value;
					this.SendPropertyChanged("ProduktBildeId");
					this.OnProduktBildeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktId", DbType="Int")]
		public System.Nullable<int> ProduktId
		{
			get
			{
				return this._ProduktId;
			}
			set
			{
				if ((this._ProduktId != value))
				{
					if (this._tblProduct.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProduktIdChanging(value);
					this.SendPropertyChanging();
					this._ProduktId = value;
					this.SendPropertyChanged("ProduktId");
					this.OnProduktIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilId", DbType="Int")]
		public System.Nullable<int> FilId
		{
			get
			{
				return this._FilId;
			}
			set
			{
				if ((this._FilId != value))
				{
					if (this._tblFile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFilIdChanging(value);
					this.SendPropertyChanging();
					this._FilId = value;
					this.SendPropertyChanged("FilId");
					this.OnFilIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int")]
		public System.Nullable<int> Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this.OnSortChanging(value);
					this.SendPropertyChanging();
					this._Sort = value;
					this.SendPropertyChanged("Sort");
					this.OnSortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeFil", DbType="NVarChar(255)")]
		public string TypeFil
		{
			get
			{
				return this._TypeFil;
			}
			set
			{
				if ((this._TypeFil != value))
				{
					this.OnTypeFilChanging(value);
					this.SendPropertyChanging();
					this._TypeFil = value;
					this.SendPropertyChanged("TypeFil");
					this.OnTypeFilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFile_tblProdctFile", Storage="_tblFile", ThisKey="FilId", OtherKey="FilId", IsForeignKey=true)]
		public tblFile tblFile
		{
			get
			{
				return this._tblFile.Entity;
			}
			set
			{
				tblFile previousValue = this._tblFile.Entity;
				if (((previousValue != value) 
							|| (this._tblFile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblFile.Entity = null;
						previousValue.tblProdctFiles.Remove(this);
					}
					this._tblFile.Entity = value;
					if ((value != null))
					{
						value.tblProdctFiles.Add(this);
						this._FilId = value.FilId;
					}
					else
					{
						this._FilId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblFile");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProduct_tblProdctFile", Storage="_tblProduct", ThisKey="ProduktId", OtherKey="ProduktId", IsForeignKey=true)]
		public tblProduct tblProduct
		{
			get
			{
				return this._tblProduct.Entity;
			}
			set
			{
				tblProduct previousValue = this._tblProduct.Entity;
				if (((previousValue != value) 
							|| (this._tblProduct.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblProduct.Entity = null;
						previousValue.tblProdctFiles.Remove(this);
					}
					this._tblProduct.Entity = value;
					if ((value != null))
					{
						value.tblProdctFiles.Add(this);
						this._ProduktId = value.ProduktId;
					}
					else
					{
						this._ProduktId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblProduct");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProduct")]
	public partial class tblProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProduktId;
		
		private int _ProduktgruppeId;
		
		private int _ProduktkategoriId;
		
		private System.DateTime _RegDato;
		
		private string _Produkt;
		
		private string _Pris;
		
		private System.Nullable<int> _ProduktNr;
		
		private string _ProduktBeskrivelse;
		
		private string _Bredde;
		
		private string _Hoyde;
		
		private string _Dybde;
		
		private string _Vekt;
		
		private System.Nullable<System.DateTime> _LagerDato;
		
		private int _WebStatus;
		
		private int _SlideStatus;
		
		private int _ButikkStatus;
		
		private int _Status;
		
		private EntitySet<tblProdctFile> _tblProdctFiles;
		
		private EntitySet<tblProductAddOn> _tblProductAddOns;
		
		private EntityRef<tblProductCategory> _tblProductCategory;
		
		private EntityRef<tblProductGroup> _tblProductGroup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduktIdChanging(int value);
    partial void OnProduktIdChanged();
    partial void OnProduktgruppeIdChanging(int value);
    partial void OnProduktgruppeIdChanged();
    partial void OnProduktkategoriIdChanging(int value);
    partial void OnProduktkategoriIdChanged();
    partial void OnRegDatoChanging(System.DateTime value);
    partial void OnRegDatoChanged();
    partial void OnProduktChanging(string value);
    partial void OnProduktChanged();
    partial void OnPrisChanging(string value);
    partial void OnPrisChanged();
    partial void OnProduktNrChanging(System.Nullable<int> value);
    partial void OnProduktNrChanged();
    partial void OnProduktBeskrivelseChanging(string value);
    partial void OnProduktBeskrivelseChanged();
    partial void OnBreddeChanging(string value);
    partial void OnBreddeChanged();
    partial void OnHoydeChanging(string value);
    partial void OnHoydeChanged();
    partial void OnDybdeChanging(string value);
    partial void OnDybdeChanged();
    partial void OnVektChanging(string value);
    partial void OnVektChanged();
    partial void OnLagerDatoChanging(System.Nullable<System.DateTime> value);
    partial void OnLagerDatoChanged();
    partial void OnWebStatusChanging(int value);
    partial void OnWebStatusChanged();
    partial void OnSlideStatusChanging(int value);
    partial void OnSlideStatusChanged();
    partial void OnButikkStatusChanging(int value);
    partial void OnButikkStatusChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    #endregion
		
		public tblProduct()
		{
			this._tblProdctFiles = new EntitySet<tblProdctFile>(new Action<tblProdctFile>(this.attach_tblProdctFiles), new Action<tblProdctFile>(this.detach_tblProdctFiles));
			this._tblProductAddOns = new EntitySet<tblProductAddOn>(new Action<tblProductAddOn>(this.attach_tblProductAddOns), new Action<tblProductAddOn>(this.detach_tblProductAddOns));
			this._tblProductCategory = default(EntityRef<tblProductCategory>);
			this._tblProductGroup = default(EntityRef<tblProductGroup>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProduktId
		{
			get
			{
				return this._ProduktId;
			}
			set
			{
				if ((this._ProduktId != value))
				{
					this.OnProduktIdChanging(value);
					this.SendPropertyChanging();
					this._ProduktId = value;
					this.SendPropertyChanged("ProduktId");
					this.OnProduktIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktgruppeId", DbType="Int NOT NULL")]
		public int ProduktgruppeId
		{
			get
			{
				return this._ProduktgruppeId;
			}
			set
			{
				if ((this._ProduktgruppeId != value))
				{
					if (this._tblProductGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProduktgruppeIdChanging(value);
					this.SendPropertyChanging();
					this._ProduktgruppeId = value;
					this.SendPropertyChanged("ProduktgruppeId");
					this.OnProduktgruppeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktkategoriId", DbType="Int NOT NULL")]
		public int ProduktkategoriId
		{
			get
			{
				return this._ProduktkategoriId;
			}
			set
			{
				if ((this._ProduktkategoriId != value))
				{
					if (this._tblProductCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProduktkategoriIdChanging(value);
					this.SendPropertyChanging();
					this._ProduktkategoriId = value;
					this.SendPropertyChanged("ProduktkategoriId");
					this.OnProduktkategoriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegDato", DbType="Date NOT NULL")]
		public System.DateTime RegDato
		{
			get
			{
				return this._RegDato;
			}
			set
			{
				if ((this._RegDato != value))
				{
					this.OnRegDatoChanging(value);
					this.SendPropertyChanging();
					this._RegDato = value;
					this.SendPropertyChanged("RegDato");
					this.OnRegDatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Produkt", DbType="NVarChar(255)")]
		public string Produkt
		{
			get
			{
				return this._Produkt;
			}
			set
			{
				if ((this._Produkt != value))
				{
					this.OnProduktChanging(value);
					this.SendPropertyChanging();
					this._Produkt = value;
					this.SendPropertyChanged("Produkt");
					this.OnProduktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pris", DbType="NVarChar(255)")]
		public string Pris
		{
			get
			{
				return this._Pris;
			}
			set
			{
				if ((this._Pris != value))
				{
					this.OnPrisChanging(value);
					this.SendPropertyChanging();
					this._Pris = value;
					this.SendPropertyChanged("Pris");
					this.OnPrisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktNr", DbType="Int")]
		public System.Nullable<int> ProduktNr
		{
			get
			{
				return this._ProduktNr;
			}
			set
			{
				if ((this._ProduktNr != value))
				{
					this.OnProduktNrChanging(value);
					this.SendPropertyChanging();
					this._ProduktNr = value;
					this.SendPropertyChanged("ProduktNr");
					this.OnProduktNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktBeskrivelse", DbType="NVarChar(MAX)")]
		public string ProduktBeskrivelse
		{
			get
			{
				return this._ProduktBeskrivelse;
			}
			set
			{
				if ((this._ProduktBeskrivelse != value))
				{
					this.OnProduktBeskrivelseChanging(value);
					this.SendPropertyChanging();
					this._ProduktBeskrivelse = value;
					this.SendPropertyChanged("ProduktBeskrivelse");
					this.OnProduktBeskrivelseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bredde", DbType="NVarChar(255)")]
		public string Bredde
		{
			get
			{
				return this._Bredde;
			}
			set
			{
				if ((this._Bredde != value))
				{
					this.OnBreddeChanging(value);
					this.SendPropertyChanging();
					this._Bredde = value;
					this.SendPropertyChanged("Bredde");
					this.OnBreddeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoyde", DbType="NVarChar(255)")]
		public string Hoyde
		{
			get
			{
				return this._Hoyde;
			}
			set
			{
				if ((this._Hoyde != value))
				{
					this.OnHoydeChanging(value);
					this.SendPropertyChanging();
					this._Hoyde = value;
					this.SendPropertyChanged("Hoyde");
					this.OnHoydeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dybde", DbType="NVarChar(255)")]
		public string Dybde
		{
			get
			{
				return this._Dybde;
			}
			set
			{
				if ((this._Dybde != value))
				{
					this.OnDybdeChanging(value);
					this.SendPropertyChanging();
					this._Dybde = value;
					this.SendPropertyChanged("Dybde");
					this.OnDybdeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vekt", DbType="NVarChar(255)")]
		public string Vekt
		{
			get
			{
				return this._Vekt;
			}
			set
			{
				if ((this._Vekt != value))
				{
					this.OnVektChanging(value);
					this.SendPropertyChanging();
					this._Vekt = value;
					this.SendPropertyChanged("Vekt");
					this.OnVektChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LagerDato", DbType="Date")]
		public System.Nullable<System.DateTime> LagerDato
		{
			get
			{
				return this._LagerDato;
			}
			set
			{
				if ((this._LagerDato != value))
				{
					this.OnLagerDatoChanging(value);
					this.SendPropertyChanging();
					this._LagerDato = value;
					this.SendPropertyChanged("LagerDato");
					this.OnLagerDatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebStatus", DbType="Int NOT NULL")]
		public int WebStatus
		{
			get
			{
				return this._WebStatus;
			}
			set
			{
				if ((this._WebStatus != value))
				{
					this.OnWebStatusChanging(value);
					this.SendPropertyChanging();
					this._WebStatus = value;
					this.SendPropertyChanged("WebStatus");
					this.OnWebStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlideStatus", DbType="Int NOT NULL")]
		public int SlideStatus
		{
			get
			{
				return this._SlideStatus;
			}
			set
			{
				if ((this._SlideStatus != value))
				{
					this.OnSlideStatusChanging(value);
					this.SendPropertyChanging();
					this._SlideStatus = value;
					this.SendPropertyChanged("SlideStatus");
					this.OnSlideStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ButikkStatus", DbType="Int NOT NULL")]
		public int ButikkStatus
		{
			get
			{
				return this._ButikkStatus;
			}
			set
			{
				if ((this._ButikkStatus != value))
				{
					this.OnButikkStatusChanging(value);
					this.SendPropertyChanging();
					this._ButikkStatus = value;
					this.SendPropertyChanged("ButikkStatus");
					this.OnButikkStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProduct_tblProdctFile", Storage="_tblProdctFiles", ThisKey="ProduktId", OtherKey="ProduktId")]
		public EntitySet<tblProdctFile> tblProdctFiles
		{
			get
			{
				return this._tblProdctFiles;
			}
			set
			{
				this._tblProdctFiles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProduct_tblProductAddOn", Storage="_tblProductAddOns", ThisKey="ProduktId", OtherKey="KnyttetId")]
		public EntitySet<tblProductAddOn> tblProductAddOns
		{
			get
			{
				return this._tblProductAddOns;
			}
			set
			{
				this._tblProductAddOns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProductCategory_tblProduct", Storage="_tblProductCategory", ThisKey="ProduktkategoriId", OtherKey="ProduktkategoriId", IsForeignKey=true)]
		public tblProductCategory tblProductCategory
		{
			get
			{
				return this._tblProductCategory.Entity;
			}
			set
			{
				tblProductCategory previousValue = this._tblProductCategory.Entity;
				if (((previousValue != value) 
							|| (this._tblProductCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblProductCategory.Entity = null;
						previousValue.tblProducts.Remove(this);
					}
					this._tblProductCategory.Entity = value;
					if ((value != null))
					{
						value.tblProducts.Add(this);
						this._ProduktkategoriId = value.ProduktkategoriId;
					}
					else
					{
						this._ProduktkategoriId = default(int);
					}
					this.SendPropertyChanged("tblProductCategory");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProductGroup_tblProduct", Storage="_tblProductGroup", ThisKey="ProduktgruppeId", OtherKey="ProduktgruppeId", IsForeignKey=true)]
		public tblProductGroup tblProductGroup
		{
			get
			{
				return this._tblProductGroup.Entity;
			}
			set
			{
				tblProductGroup previousValue = this._tblProductGroup.Entity;
				if (((previousValue != value) 
							|| (this._tblProductGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblProductGroup.Entity = null;
						previousValue.tblProducts.Remove(this);
					}
					this._tblProductGroup.Entity = value;
					if ((value != null))
					{
						value.tblProducts.Add(this);
						this._ProduktgruppeId = value.ProduktgruppeId;
					}
					else
					{
						this._ProduktgruppeId = default(int);
					}
					this.SendPropertyChanged("tblProductGroup");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblProdctFiles(tblProdctFile entity)
		{
			this.SendPropertyChanging();
			entity.tblProduct = this;
		}
		
		private void detach_tblProdctFiles(tblProdctFile entity)
		{
			this.SendPropertyChanging();
			entity.tblProduct = null;
		}
		
		private void attach_tblProductAddOns(tblProductAddOn entity)
		{
			this.SendPropertyChanging();
			entity.tblProduct = this;
		}
		
		private void detach_tblProductAddOns(tblProductAddOn entity)
		{
			this.SendPropertyChanging();
			entity.tblProduct = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProductAddOn")]
	public partial class tblProductAddOn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TilleggId;
		
		private System.Nullable<int> _KnyttetId;
		
		private string _TilleggType;
		
		private string _TilleggGruppe;
		
		private string _TilleggTekst;
		
		private System.Nullable<int> _TilleggTall;
		
		private string _TilleggMerknad;
		
		private EntityRef<tblProduct> _tblProduct;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTilleggIdChanging(int value);
    partial void OnTilleggIdChanged();
    partial void OnKnyttetIdChanging(System.Nullable<int> value);
    partial void OnKnyttetIdChanged();
    partial void OnTilleggTypeChanging(string value);
    partial void OnTilleggTypeChanged();
    partial void OnTilleggGruppeChanging(string value);
    partial void OnTilleggGruppeChanged();
    partial void OnTilleggTekstChanging(string value);
    partial void OnTilleggTekstChanged();
    partial void OnTilleggTallChanging(System.Nullable<int> value);
    partial void OnTilleggTallChanged();
    partial void OnTilleggMerknadChanging(string value);
    partial void OnTilleggMerknadChanged();
    #endregion
		
		public tblProductAddOn()
		{
			this._tblProduct = default(EntityRef<tblProduct>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TilleggId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TilleggId
		{
			get
			{
				return this._TilleggId;
			}
			set
			{
				if ((this._TilleggId != value))
				{
					this.OnTilleggIdChanging(value);
					this.SendPropertyChanging();
					this._TilleggId = value;
					this.SendPropertyChanged("TilleggId");
					this.OnTilleggIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KnyttetId", DbType="Int")]
		public System.Nullable<int> KnyttetId
		{
			get
			{
				return this._KnyttetId;
			}
			set
			{
				if ((this._KnyttetId != value))
				{
					if (this._tblProduct.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKnyttetIdChanging(value);
					this.SendPropertyChanging();
					this._KnyttetId = value;
					this.SendPropertyChanged("KnyttetId");
					this.OnKnyttetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TilleggType", DbType="NVarChar(255)")]
		public string TilleggType
		{
			get
			{
				return this._TilleggType;
			}
			set
			{
				if ((this._TilleggType != value))
				{
					this.OnTilleggTypeChanging(value);
					this.SendPropertyChanging();
					this._TilleggType = value;
					this.SendPropertyChanged("TilleggType");
					this.OnTilleggTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TilleggGruppe", DbType="NVarChar(255)")]
		public string TilleggGruppe
		{
			get
			{
				return this._TilleggGruppe;
			}
			set
			{
				if ((this._TilleggGruppe != value))
				{
					this.OnTilleggGruppeChanging(value);
					this.SendPropertyChanging();
					this._TilleggGruppe = value;
					this.SendPropertyChanged("TilleggGruppe");
					this.OnTilleggGruppeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TilleggTekst", DbType="NVarChar(255)")]
		public string TilleggTekst
		{
			get
			{
				return this._TilleggTekst;
			}
			set
			{
				if ((this._TilleggTekst != value))
				{
					this.OnTilleggTekstChanging(value);
					this.SendPropertyChanging();
					this._TilleggTekst = value;
					this.SendPropertyChanged("TilleggTekst");
					this.OnTilleggTekstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TilleggTall", DbType="Int")]
		public System.Nullable<int> TilleggTall
		{
			get
			{
				return this._TilleggTall;
			}
			set
			{
				if ((this._TilleggTall != value))
				{
					this.OnTilleggTallChanging(value);
					this.SendPropertyChanging();
					this._TilleggTall = value;
					this.SendPropertyChanged("TilleggTall");
					this.OnTilleggTallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TilleggMerknad", DbType="NVarChar(MAX)")]
		public string TilleggMerknad
		{
			get
			{
				return this._TilleggMerknad;
			}
			set
			{
				if ((this._TilleggMerknad != value))
				{
					this.OnTilleggMerknadChanging(value);
					this.SendPropertyChanging();
					this._TilleggMerknad = value;
					this.SendPropertyChanged("TilleggMerknad");
					this.OnTilleggMerknadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProduct_tblProductAddOn", Storage="_tblProduct", ThisKey="KnyttetId", OtherKey="ProduktId", IsForeignKey=true)]
		public tblProduct tblProduct
		{
			get
			{
				return this._tblProduct.Entity;
			}
			set
			{
				tblProduct previousValue = this._tblProduct.Entity;
				if (((previousValue != value) 
							|| (this._tblProduct.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblProduct.Entity = null;
						previousValue.tblProductAddOns.Remove(this);
					}
					this._tblProduct.Entity = value;
					if ((value != null))
					{
						value.tblProductAddOns.Add(this);
						this._KnyttetId = value.ProduktId;
					}
					else
					{
						this._KnyttetId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblProduct");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUser")]
	public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BrukerId;
		
		private int _BrukerTypeId;
		
		private System.Nullable<int> _FirmaId;
		
		private System.Nullable<int> _KnyttetId;
		
		private System.Nullable<System.DateTime> _RegDato;
		
		private System.Nullable<int> _Brukernr;
		
		private string _Firma;
		
		private string _Kontaktperson;
		
		private string _Fornavn;
		
		private string _Etternavn;
		
		private string _Tittel;
		
		private string _Gateadresse;
		
		private string _Postnr1;
		
		private string _Sted1;
		
		private string _Land1;
		
		private string _Postadresse;
		
		private string _Postnr2;
		
		private string _Sted2;
		
		private string _Land2;
		
		private string _Telefon;
		
		private string _Telefaks;
		
		private string _Mobil;
		
		private string _Epost;
		
		private string _Web;
		
		private string _Foretaksnummer;
		
		private string _Mva;
		
		private System.Nullable<System.DateTime> _Fodselsdato;
		
		private string _Kjonn;
		
		private string _Brukernavn;
		
		private string _Passord;
		
		private System.Nullable<decimal> _Lat;
		
		private System.Nullable<decimal> _Lng;
		
		private string _Aktiveringskode;
		
		private string _Innhold;
		
		private string _Nyhetsmail;
		
		private System.Nullable<int> _Status;
		
		private string _KundeId;
		
		private System.Nullable<int> _LanguageId;
		
		private EntityRef<tblLanguage> _tblLanguage;
		
		private EntityRef<tblUserType> _tblUserType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBrukerIdChanging(int value);
    partial void OnBrukerIdChanged();
    partial void OnBrukerTypeIdChanging(int value);
    partial void OnBrukerTypeIdChanged();
    partial void OnFirmaIdChanging(System.Nullable<int> value);
    partial void OnFirmaIdChanged();
    partial void OnKnyttetIdChanging(System.Nullable<int> value);
    partial void OnKnyttetIdChanged();
    partial void OnRegDatoChanging(System.Nullable<System.DateTime> value);
    partial void OnRegDatoChanged();
    partial void OnBrukernrChanging(System.Nullable<int> value);
    partial void OnBrukernrChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    partial void OnKontaktpersonChanging(string value);
    partial void OnKontaktpersonChanged();
    partial void OnFornavnChanging(string value);
    partial void OnFornavnChanged();
    partial void OnEtternavnChanging(string value);
    partial void OnEtternavnChanged();
    partial void OnTittelChanging(string value);
    partial void OnTittelChanged();
    partial void OnGateadresseChanging(string value);
    partial void OnGateadresseChanged();
    partial void OnPostnr1Changing(string value);
    partial void OnPostnr1Changed();
    partial void OnSted1Changing(string value);
    partial void OnSted1Changed();
    partial void OnLand1Changing(string value);
    partial void OnLand1Changed();
    partial void OnPostadresseChanging(string value);
    partial void OnPostadresseChanged();
    partial void OnPostnr2Changing(string value);
    partial void OnPostnr2Changed();
    partial void OnSted2Changing(string value);
    partial void OnSted2Changed();
    partial void OnLand2Changing(string value);
    partial void OnLand2Changed();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnTelefaksChanging(string value);
    partial void OnTelefaksChanged();
    partial void OnMobilChanging(string value);
    partial void OnMobilChanged();
    partial void OnEpostChanging(string value);
    partial void OnEpostChanged();
    partial void OnWebChanging(string value);
    partial void OnWebChanged();
    partial void OnForetaksnummerChanging(string value);
    partial void OnForetaksnummerChanged();
    partial void OnMvaChanging(string value);
    partial void OnMvaChanged();
    partial void OnFodselsdatoChanging(System.Nullable<System.DateTime> value);
    partial void OnFodselsdatoChanged();
    partial void OnKjonnChanging(string value);
    partial void OnKjonnChanged();
    partial void OnBrukernavnChanging(string value);
    partial void OnBrukernavnChanged();
    partial void OnPassordChanging(string value);
    partial void OnPassordChanged();
    partial void OnLatChanging(System.Nullable<decimal> value);
    partial void OnLatChanged();
    partial void OnLngChanging(System.Nullable<decimal> value);
    partial void OnLngChanged();
    partial void OnAktiveringskodeChanging(string value);
    partial void OnAktiveringskodeChanged();
    partial void OnInnholdChanging(string value);
    partial void OnInnholdChanged();
    partial void OnNyhetsmailChanging(string value);
    partial void OnNyhetsmailChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnKundeIdChanging(string value);
    partial void OnKundeIdChanged();
    partial void OnLanguageIdChanging(System.Nullable<int> value);
    partial void OnLanguageIdChanged();
    #endregion
		
		public tblUser()
		{
			this._tblLanguage = default(EntityRef<tblLanguage>);
			this._tblUserType = default(EntityRef<tblUserType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrukerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BrukerId
		{
			get
			{
				return this._BrukerId;
			}
			set
			{
				if ((this._BrukerId != value))
				{
					this.OnBrukerIdChanging(value);
					this.SendPropertyChanging();
					this._BrukerId = value;
					this.SendPropertyChanged("BrukerId");
					this.OnBrukerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrukerTypeId", DbType="Int NOT NULL")]
		public int BrukerTypeId
		{
			get
			{
				return this._BrukerTypeId;
			}
			set
			{
				if ((this._BrukerTypeId != value))
				{
					if (this._tblUserType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBrukerTypeIdChanging(value);
					this.SendPropertyChanging();
					this._BrukerTypeId = value;
					this.SendPropertyChanged("BrukerTypeId");
					this.OnBrukerTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaId", DbType="Int")]
		public System.Nullable<int> FirmaId
		{
			get
			{
				return this._FirmaId;
			}
			set
			{
				if ((this._FirmaId != value))
				{
					this.OnFirmaIdChanging(value);
					this.SendPropertyChanging();
					this._FirmaId = value;
					this.SendPropertyChanged("FirmaId");
					this.OnFirmaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KnyttetId", DbType="Int")]
		public System.Nullable<int> KnyttetId
		{
			get
			{
				return this._KnyttetId;
			}
			set
			{
				if ((this._KnyttetId != value))
				{
					this.OnKnyttetIdChanging(value);
					this.SendPropertyChanging();
					this._KnyttetId = value;
					this.SendPropertyChanged("KnyttetId");
					this.OnKnyttetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegDato", DbType="DateTime")]
		public System.Nullable<System.DateTime> RegDato
		{
			get
			{
				return this._RegDato;
			}
			set
			{
				if ((this._RegDato != value))
				{
					this.OnRegDatoChanging(value);
					this.SendPropertyChanging();
					this._RegDato = value;
					this.SendPropertyChanged("RegDato");
					this.OnRegDatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brukernr", DbType="Int")]
		public System.Nullable<int> Brukernr
		{
			get
			{
				return this._Brukernr;
			}
			set
			{
				if ((this._Brukernr != value))
				{
					this.OnBrukernrChanging(value);
					this.SendPropertyChanging();
					this._Brukernr = value;
					this.SendPropertyChanged("Brukernr");
					this.OnBrukernrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="NVarChar(255)")]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kontaktperson", DbType="NVarChar(255)")]
		public string Kontaktperson
		{
			get
			{
				return this._Kontaktperson;
			}
			set
			{
				if ((this._Kontaktperson != value))
				{
					this.OnKontaktpersonChanging(value);
					this.SendPropertyChanging();
					this._Kontaktperson = value;
					this.SendPropertyChanged("Kontaktperson");
					this.OnKontaktpersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fornavn", DbType="NVarChar(255)")]
		public string Fornavn
		{
			get
			{
				return this._Fornavn;
			}
			set
			{
				if ((this._Fornavn != value))
				{
					this.OnFornavnChanging(value);
					this.SendPropertyChanging();
					this._Fornavn = value;
					this.SendPropertyChanged("Fornavn");
					this.OnFornavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etternavn", DbType="NVarChar(255)")]
		public string Etternavn
		{
			get
			{
				return this._Etternavn;
			}
			set
			{
				if ((this._Etternavn != value))
				{
					this.OnEtternavnChanging(value);
					this.SendPropertyChanging();
					this._Etternavn = value;
					this.SendPropertyChanged("Etternavn");
					this.OnEtternavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tittel", DbType="NVarChar(255)")]
		public string Tittel
		{
			get
			{
				return this._Tittel;
			}
			set
			{
				if ((this._Tittel != value))
				{
					this.OnTittelChanging(value);
					this.SendPropertyChanging();
					this._Tittel = value;
					this.SendPropertyChanged("Tittel");
					this.OnTittelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gateadresse", DbType="NVarChar(255)")]
		public string Gateadresse
		{
			get
			{
				return this._Gateadresse;
			}
			set
			{
				if ((this._Gateadresse != value))
				{
					this.OnGateadresseChanging(value);
					this.SendPropertyChanging();
					this._Gateadresse = value;
					this.SendPropertyChanged("Gateadresse");
					this.OnGateadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postnr1", DbType="NVarChar(255)")]
		public string Postnr1
		{
			get
			{
				return this._Postnr1;
			}
			set
			{
				if ((this._Postnr1 != value))
				{
					this.OnPostnr1Changing(value);
					this.SendPropertyChanging();
					this._Postnr1 = value;
					this.SendPropertyChanged("Postnr1");
					this.OnPostnr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sted1", DbType="NVarChar(255)")]
		public string Sted1
		{
			get
			{
				return this._Sted1;
			}
			set
			{
				if ((this._Sted1 != value))
				{
					this.OnSted1Changing(value);
					this.SendPropertyChanging();
					this._Sted1 = value;
					this.SendPropertyChanged("Sted1");
					this.OnSted1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Land1", DbType="NVarChar(255)")]
		public string Land1
		{
			get
			{
				return this._Land1;
			}
			set
			{
				if ((this._Land1 != value))
				{
					this.OnLand1Changing(value);
					this.SendPropertyChanging();
					this._Land1 = value;
					this.SendPropertyChanged("Land1");
					this.OnLand1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postadresse", DbType="NVarChar(255)")]
		public string Postadresse
		{
			get
			{
				return this._Postadresse;
			}
			set
			{
				if ((this._Postadresse != value))
				{
					this.OnPostadresseChanging(value);
					this.SendPropertyChanging();
					this._Postadresse = value;
					this.SendPropertyChanged("Postadresse");
					this.OnPostadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postnr2", DbType="NVarChar(255)")]
		public string Postnr2
		{
			get
			{
				return this._Postnr2;
			}
			set
			{
				if ((this._Postnr2 != value))
				{
					this.OnPostnr2Changing(value);
					this.SendPropertyChanging();
					this._Postnr2 = value;
					this.SendPropertyChanged("Postnr2");
					this.OnPostnr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sted2", DbType="NVarChar(255)")]
		public string Sted2
		{
			get
			{
				return this._Sted2;
			}
			set
			{
				if ((this._Sted2 != value))
				{
					this.OnSted2Changing(value);
					this.SendPropertyChanging();
					this._Sted2 = value;
					this.SendPropertyChanged("Sted2");
					this.OnSted2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Land2", DbType="NVarChar(255)")]
		public string Land2
		{
			get
			{
				return this._Land2;
			}
			set
			{
				if ((this._Land2 != value))
				{
					this.OnLand2Changing(value);
					this.SendPropertyChanging();
					this._Land2 = value;
					this.SendPropertyChanged("Land2");
					this.OnLand2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(255)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefaks", DbType="NVarChar(255)")]
		public string Telefaks
		{
			get
			{
				return this._Telefaks;
			}
			set
			{
				if ((this._Telefaks != value))
				{
					this.OnTelefaksChanging(value);
					this.SendPropertyChanging();
					this._Telefaks = value;
					this.SendPropertyChanged("Telefaks");
					this.OnTelefaksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobil", DbType="NVarChar(255)")]
		public string Mobil
		{
			get
			{
				return this._Mobil;
			}
			set
			{
				if ((this._Mobil != value))
				{
					this.OnMobilChanging(value);
					this.SendPropertyChanging();
					this._Mobil = value;
					this.SendPropertyChanged("Mobil");
					this.OnMobilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Epost", DbType="NVarChar(255)")]
		public string Epost
		{
			get
			{
				return this._Epost;
			}
			set
			{
				if ((this._Epost != value))
				{
					this.OnEpostChanging(value);
					this.SendPropertyChanging();
					this._Epost = value;
					this.SendPropertyChanged("Epost");
					this.OnEpostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="NVarChar(255)")]
		public string Web
		{
			get
			{
				return this._Web;
			}
			set
			{
				if ((this._Web != value))
				{
					this.OnWebChanging(value);
					this.SendPropertyChanging();
					this._Web = value;
					this.SendPropertyChanged("Web");
					this.OnWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foretaksnummer", DbType="NVarChar(255)")]
		public string Foretaksnummer
		{
			get
			{
				return this._Foretaksnummer;
			}
			set
			{
				if ((this._Foretaksnummer != value))
				{
					this.OnForetaksnummerChanging(value);
					this.SendPropertyChanging();
					this._Foretaksnummer = value;
					this.SendPropertyChanged("Foretaksnummer");
					this.OnForetaksnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mva", DbType="NVarChar(255)")]
		public string Mva
		{
			get
			{
				return this._Mva;
			}
			set
			{
				if ((this._Mva != value))
				{
					this.OnMvaChanging(value);
					this.SendPropertyChanging();
					this._Mva = value;
					this.SendPropertyChanged("Mva");
					this.OnMvaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fodselsdato", DbType="Date")]
		public System.Nullable<System.DateTime> Fodselsdato
		{
			get
			{
				return this._Fodselsdato;
			}
			set
			{
				if ((this._Fodselsdato != value))
				{
					this.OnFodselsdatoChanging(value);
					this.SendPropertyChanging();
					this._Fodselsdato = value;
					this.SendPropertyChanged("Fodselsdato");
					this.OnFodselsdatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kjonn", DbType="NVarChar(255)")]
		public string Kjonn
		{
			get
			{
				return this._Kjonn;
			}
			set
			{
				if ((this._Kjonn != value))
				{
					this.OnKjonnChanging(value);
					this.SendPropertyChanging();
					this._Kjonn = value;
					this.SendPropertyChanged("Kjonn");
					this.OnKjonnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brukernavn", DbType="NVarChar(255)")]
		public string Brukernavn
		{
			get
			{
				return this._Brukernavn;
			}
			set
			{
				if ((this._Brukernavn != value))
				{
					this.OnBrukernavnChanging(value);
					this.SendPropertyChanging();
					this._Brukernavn = value;
					this.SendPropertyChanged("Brukernavn");
					this.OnBrukernavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passord", DbType="NVarChar(255)")]
		public string Passord
		{
			get
			{
				return this._Passord;
			}
			set
			{
				if ((this._Passord != value))
				{
					this.OnPassordChanging(value);
					this.SendPropertyChanging();
					this._Passord = value;
					this.SendPropertyChanged("Passord");
					this.OnPassordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Decimal(28,15)")]
		public System.Nullable<decimal> Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this.OnLatChanging(value);
					this.SendPropertyChanging();
					this._Lat = value;
					this.SendPropertyChanged("Lat");
					this.OnLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lng", DbType="Decimal(28,15)")]
		public System.Nullable<decimal> Lng
		{
			get
			{
				return this._Lng;
			}
			set
			{
				if ((this._Lng != value))
				{
					this.OnLngChanging(value);
					this.SendPropertyChanging();
					this._Lng = value;
					this.SendPropertyChanged("Lng");
					this.OnLngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktiveringskode", DbType="NVarChar(255)")]
		public string Aktiveringskode
		{
			get
			{
				return this._Aktiveringskode;
			}
			set
			{
				if ((this._Aktiveringskode != value))
				{
					this.OnAktiveringskodeChanging(value);
					this.SendPropertyChanging();
					this._Aktiveringskode = value;
					this.SendPropertyChanged("Aktiveringskode");
					this.OnAktiveringskodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Innhold", DbType="NVarChar(MAX)")]
		public string Innhold
		{
			get
			{
				return this._Innhold;
			}
			set
			{
				if ((this._Innhold != value))
				{
					this.OnInnholdChanging(value);
					this.SendPropertyChanging();
					this._Innhold = value;
					this.SendPropertyChanged("Innhold");
					this.OnInnholdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nyhetsmail", DbType="NVarChar(255)")]
		public string Nyhetsmail
		{
			get
			{
				return this._Nyhetsmail;
			}
			set
			{
				if ((this._Nyhetsmail != value))
				{
					this.OnNyhetsmailChanging(value);
					this.SendPropertyChanging();
					this._Nyhetsmail = value;
					this.SendPropertyChanged("Nyhetsmail");
					this.OnNyhetsmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KundeId", DbType="NVarChar(255)")]
		public string KundeId
		{
			get
			{
				return this._KundeId;
			}
			set
			{
				if ((this._KundeId != value))
				{
					this.OnKundeIdChanging(value);
					this.SendPropertyChanging();
					this._KundeId = value;
					this.SendPropertyChanged("KundeId");
					this.OnKundeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageId", DbType="Int")]
		public System.Nullable<int> LanguageId
		{
			get
			{
				return this._LanguageId;
			}
			set
			{
				if ((this._LanguageId != value))
				{
					if (this._tblLanguage.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLanguageIdChanging(value);
					this.SendPropertyChanging();
					this._LanguageId = value;
					this.SendPropertyChanged("LanguageId");
					this.OnLanguageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLanguage_tblUser", Storage="_tblLanguage", ThisKey="LanguageId", OtherKey="LanguageId", IsForeignKey=true)]
		public tblLanguage tblLanguage
		{
			get
			{
				return this._tblLanguage.Entity;
			}
			set
			{
				tblLanguage previousValue = this._tblLanguage.Entity;
				if (((previousValue != value) 
							|| (this._tblLanguage.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLanguage.Entity = null;
						previousValue.tblUsers.Remove(this);
					}
					this._tblLanguage.Entity = value;
					if ((value != null))
					{
						value.tblUsers.Add(this);
						this._LanguageId = value.LanguageId;
					}
					else
					{
						this._LanguageId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblLanguage");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUserType_tblUser", Storage="_tblUserType", ThisKey="BrukerTypeId", OtherKey="BrukertypeId", IsForeignKey=true)]
		public tblUserType tblUserType
		{
			get
			{
				return this._tblUserType.Entity;
			}
			set
			{
				tblUserType previousValue = this._tblUserType.Entity;
				if (((previousValue != value) 
							|| (this._tblUserType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUserType.Entity = null;
						previousValue.tblUsers.Remove(this);
					}
					this._tblUserType.Entity = value;
					if ((value != null))
					{
						value.tblUsers.Add(this);
						this._BrukerTypeId = value.BrukertypeId;
					}
					else
					{
						this._BrukerTypeId = default(int);
					}
					this.SendPropertyChanged("tblUserType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUserType")]
	public partial class tblUserType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BrukertypeId;
		
		private int _BrukertypeNr;
		
		private string _Type;
		
		private string _Kategori;
		
		private EntitySet<tblUser> _tblUsers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBrukertypeIdChanging(int value);
    partial void OnBrukertypeIdChanged();
    partial void OnBrukertypeNrChanging(int value);
    partial void OnBrukertypeNrChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnKategoriChanging(string value);
    partial void OnKategoriChanged();
    #endregion
		
		public tblUserType()
		{
			this._tblUsers = new EntitySet<tblUser>(new Action<tblUser>(this.attach_tblUsers), new Action<tblUser>(this.detach_tblUsers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrukertypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BrukertypeId
		{
			get
			{
				return this._BrukertypeId;
			}
			set
			{
				if ((this._BrukertypeId != value))
				{
					this.OnBrukertypeIdChanging(value);
					this.SendPropertyChanging();
					this._BrukertypeId = value;
					this.SendPropertyChanged("BrukertypeId");
					this.OnBrukertypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrukertypeNr", DbType="Int NOT NULL")]
		public int BrukertypeNr
		{
			get
			{
				return this._BrukertypeNr;
			}
			set
			{
				if ((this._BrukertypeNr != value))
				{
					this.OnBrukertypeNrChanging(value);
					this.SendPropertyChanging();
					this._BrukertypeNr = value;
					this.SendPropertyChanged("BrukertypeNr");
					this.OnBrukertypeNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(255)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategori", DbType="NVarChar(255)")]
		public string Kategori
		{
			get
			{
				return this._Kategori;
			}
			set
			{
				if ((this._Kategori != value))
				{
					this.OnKategoriChanging(value);
					this.SendPropertyChanging();
					this._Kategori = value;
					this.SendPropertyChanged("Kategori");
					this.OnKategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUserType_tblUser", Storage="_tblUsers", ThisKey="BrukertypeId", OtherKey="BrukerTypeId")]
		public EntitySet<tblUser> tblUsers
		{
			get
			{
				return this._tblUsers;
			}
			set
			{
				this._tblUsers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblUsers(tblUser entity)
		{
			this.SendPropertyChanging();
			entity.tblUserType = this;
		}
		
		private void detach_tblUsers(tblUser entity)
		{
			this.SendPropertyChanging();
			entity.tblUserType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProductCategory")]
	public partial class tblProductCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProduktkategoriId;
		
		private System.Nullable<int> _ProduktkategoriNr;
		
		private string _Produktkategori;
		
		private int _Status;
		
		private EntitySet<tblProduct> _tblProducts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduktkategoriIdChanging(int value);
    partial void OnProduktkategoriIdChanged();
    partial void OnProduktkategoriNrChanging(System.Nullable<int> value);
    partial void OnProduktkategoriNrChanged();
    partial void OnProduktkategoriChanging(string value);
    partial void OnProduktkategoriChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    #endregion
		
		public tblProductCategory()
		{
			this._tblProducts = new EntitySet<tblProduct>(new Action<tblProduct>(this.attach_tblProducts), new Action<tblProduct>(this.detach_tblProducts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktkategoriId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProduktkategoriId
		{
			get
			{
				return this._ProduktkategoriId;
			}
			set
			{
				if ((this._ProduktkategoriId != value))
				{
					this.OnProduktkategoriIdChanging(value);
					this.SendPropertyChanging();
					this._ProduktkategoriId = value;
					this.SendPropertyChanged("ProduktkategoriId");
					this.OnProduktkategoriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktkategoriNr", DbType="Int")]
		public System.Nullable<int> ProduktkategoriNr
		{
			get
			{
				return this._ProduktkategoriNr;
			}
			set
			{
				if ((this._ProduktkategoriNr != value))
				{
					this.OnProduktkategoriNrChanging(value);
					this.SendPropertyChanging();
					this._ProduktkategoriNr = value;
					this.SendPropertyChanged("ProduktkategoriNr");
					this.OnProduktkategoriNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Produktkategori", DbType="NVarChar(255)")]
		public string Produktkategori
		{
			get
			{
				return this._Produktkategori;
			}
			set
			{
				if ((this._Produktkategori != value))
				{
					this.OnProduktkategoriChanging(value);
					this.SendPropertyChanging();
					this._Produktkategori = value;
					this.SendPropertyChanged("Produktkategori");
					this.OnProduktkategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProductCategory_tblProduct", Storage="_tblProducts", ThisKey="ProduktkategoriId", OtherKey="ProduktkategoriId")]
		public EntitySet<tblProduct> tblProducts
		{
			get
			{
				return this._tblProducts;
			}
			set
			{
				this._tblProducts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblProducts(tblProduct entity)
		{
			this.SendPropertyChanging();
			entity.tblProductCategory = this;
		}
		
		private void detach_tblProducts(tblProduct entity)
		{
			this.SendPropertyChanging();
			entity.tblProductCategory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProductGroup")]
	public partial class tblProductGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProduktgruppeId;
		
		private System.Nullable<int> _ProduktgruppeNr;
		
		private string _Produktgruppe;
		
		private string _ProduktgruppeInfo;
		
		private int _Status;
		
		private EntitySet<tblProduct> _tblProducts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduktgruppeIdChanging(int value);
    partial void OnProduktgruppeIdChanged();
    partial void OnProduktgruppeNrChanging(System.Nullable<int> value);
    partial void OnProduktgruppeNrChanged();
    partial void OnProduktgruppeChanging(string value);
    partial void OnProduktgruppeChanged();
    partial void OnProduktgruppeInfoChanging(string value);
    partial void OnProduktgruppeInfoChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    #endregion
		
		public tblProductGroup()
		{
			this._tblProducts = new EntitySet<tblProduct>(new Action<tblProduct>(this.attach_tblProducts), new Action<tblProduct>(this.detach_tblProducts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktgruppeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProduktgruppeId
		{
			get
			{
				return this._ProduktgruppeId;
			}
			set
			{
				if ((this._ProduktgruppeId != value))
				{
					this.OnProduktgruppeIdChanging(value);
					this.SendPropertyChanging();
					this._ProduktgruppeId = value;
					this.SendPropertyChanged("ProduktgruppeId");
					this.OnProduktgruppeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktgruppeNr", DbType="Int")]
		public System.Nullable<int> ProduktgruppeNr
		{
			get
			{
				return this._ProduktgruppeNr;
			}
			set
			{
				if ((this._ProduktgruppeNr != value))
				{
					this.OnProduktgruppeNrChanging(value);
					this.SendPropertyChanging();
					this._ProduktgruppeNr = value;
					this.SendPropertyChanged("ProduktgruppeNr");
					this.OnProduktgruppeNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Produktgruppe", DbType="NVarChar(255)")]
		public string Produktgruppe
		{
			get
			{
				return this._Produktgruppe;
			}
			set
			{
				if ((this._Produktgruppe != value))
				{
					this.OnProduktgruppeChanging(value);
					this.SendPropertyChanging();
					this._Produktgruppe = value;
					this.SendPropertyChanged("Produktgruppe");
					this.OnProduktgruppeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktgruppeInfo", DbType="NVarChar(255)")]
		public string ProduktgruppeInfo
		{
			get
			{
				return this._ProduktgruppeInfo;
			}
			set
			{
				if ((this._ProduktgruppeInfo != value))
				{
					this.OnProduktgruppeInfoChanging(value);
					this.SendPropertyChanging();
					this._ProduktgruppeInfo = value;
					this.SendPropertyChanged("ProduktgruppeInfo");
					this.OnProduktgruppeInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProductGroup_tblProduct", Storage="_tblProducts", ThisKey="ProduktgruppeId", OtherKey="ProduktgruppeId")]
		public EntitySet<tblProduct> tblProducts
		{
			get
			{
				return this._tblProducts;
			}
			set
			{
				this._tblProducts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblProducts(tblProduct entity)
		{
			this.SendPropertyChanging();
			entity.tblProductGroup = this;
		}
		
		private void detach_tblProducts(tblProduct entity)
		{
			this.SendPropertyChanging();
			entity.tblProductGroup = null;
		}
	}
}
#pragma warning restore 1591
